name: Publish Sourcemaps to New Relic

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install New Relic CLI
        run: npm install -g @newrelic/publish-sourcemap

      - name: Obfuscate code
        run: npm run obfuscate

      - name: Publish app.js sourcemap
        run: |
          publish-sourcemap dist/app.js.map https://iikier.github.io/obfuscator-poc/dist/app.js --applicationId ${{ secrets.NEW_RELIC_APP_ID }} --apiKey ${{ secrets.NEW_RELIC_USER_API_KEY }}
      
      - name: Publish storage.js sourcemap
        run: |
          publish-sourcemap dist/storage.js.map https://iikier.github.io/obfuscator-poc/dist/storage.js --applicationId ${{ secrets.NEW_RELIC_APP_ID }} --apiKey ${{ secrets.NEW_RELIC_USER_API_KEY }}

      - name: Publish todoManager.js sourcemap
        run: |
          publish-sourcemap dist/todoManager.js.map https://iikier.github.io/obfuscator-poc/dist/todoManager.js --applicationId ${{ secrets.NEW_RELIC_APP_ID }} --apiKey ${{ secrets.NEW_RELIC_USER_API_KEY }}

      - name: Publish ui.js sourcemap
        run: |
          publish-sourcemap dist/ui.js.map https://iikier.github.io/obfuscator-poc/dist/ui.js --applicationId ${{ secrets.NEW_RELIC_APP_ID }} --apiKey ${{ secrets.NEW_RELIC_USER_API_KEY }} 